In [24]:
import numpy as np
import math
import pandas as pd


In [44]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
type(mat)

list

In [48]:
mat[1]

[5, 6, 7, 8, 9]

In [35]:
alpha=10
math.sin(alpha)


-0.5440211108893698

In [36]:
math.cos(alpha) 


-0.8390715290764524

In [37]:
math.factorial(alpha) 


3628800

In [38]:
math.pi

3.141592653589793

In [39]:
math.degrees(math.pi)

180.0

In [42]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [25]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)
print(lst.max())

8150


In [3]:
print(lst.min())

1280


In [4]:
filtro = lst > 4999
maggiori=lst[filtro]
print(maggiori)

[5500 7200 6410 8150 7100 5350]


In [5]:
maggiori.size

6

In [6]:
filtro1 = lst < 3000
minori=lst[filtro1]
print(minori)

[2000 1280 1900 2500]


In [7]:
minori.size

4

In [8]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}

In [9]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

In [11]:
fatturati_dict[1997] 

12000

In [14]:
type(fatturati_dict[1997])

int

In [12]:
fatturati_series[1997]

12000

In [13]:
type(fatturati_series[1997])

numpy.int64

In [16]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )
stipendi*2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [23]:
stipendi1 = [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000]
stipendi_raddoppiati = []
for stipendio in stipendi:
    stipendi_raddoppiati.append(stipendio * 2)

print(stipendi_raddoppiati)

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
